#!/bin/bash 

#
# Extract info from various files for use by StaMPS
#
# make sure you have (files): intf_SB_list , date_dsc_no_master.txt

raw=$1
topo=$2
heading=$3
master_date=$4

SLC_OSF="1"  # check if oversampled or not
echo $SLC_OSF > slc_osfactor.1.in                 # put oversampling factor to file 

# Create other input files for PS SBAS candidates, make sure folder stack/PS has been processed, if not:
#cp ../../bperp.1.in .
awk '{printf("%0.4f\n", $5)}' $raw/baseline_table_no_master.dat > bperp.1.in
#cp ../../day.1.in .
cp date_no_master.txt day.1.in
#cp ../../master_day.1.in .
echo "$master_date" > master_day.1.in #put your date of super master here

rm -f ifgday.1.in
cat intf_SB_list.in | while read date_master date_slave
do
echo $date_master $date_slave >> ifgday.1.in
done

echo $heading > heading.1.in # for Sentinel-1 ASC: "-12.00707218611660e"
cp $raw/*LED .
cp $raw/*.PRM .
cp $topo/master.PRM .
ln -s -f $topo/trans.dat .
ln -s -f $topo/dem.grd .
ln -s -f $raw/scatter_SB.grd .
grep radar_wavelength $topo/master.PRM | awk '{print $3}' > lambda.1.in # in meters
